import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Configure Anek Bangla font
const anekBangla = localFont({
  src: [
    {
      path: "./fonts/Anek-Bangla-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/Anek-Bangla-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Anek-Bangla-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/Anek-Bangla-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Anek-Bangla-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Anek-Bangla-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Anek-Bangla-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Anek-Bangla-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/FoundersGrotesk-Semibold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-anek-bangla",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={anekBangla.variable}>{children}</body>
    </html>
  );
}
