import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Configure DM Sans font
const dmSans = localFont({
  src: [
    {
      path: "./fonts/DMSans-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/DMSans-ThinItalic.ttf",
      weight: "100",
      style: "italic",
    },
    {
      path: "./fonts/DMSans-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/DMSans-LightItalic.ttf",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/DMSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/DMSans-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/DMSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/DMSans-MediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/DMSans-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/DMSans-SemiBoldItalic.ttf",
      weight: "600",
      style: "italic",
    },
    {
      path: "./fonts/DMSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/DMSans-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/DMSans-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/DMSans-ExtraBoldItalic.ttf",
      weight: "800",
      style: "italic",
    },
    {
      path: "./fonts/DMSans-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/DMSans-BlackItalic.ttf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} font-dm-sans`}>{children}</body>
    </html>
  );
}
